# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0002_news_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson1', models.TextField()),
                ('lesson2', models.TextField()),
                ('lesson3', models.TextField()),
                ('lesson4', models.TextField()),
                ('lesson5', models.TextField()),
                ('lesson6', models.TextField()),
                ('lesson7', models.TextField()),
                ('lesson8', models.TextField()),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbou.Form')),
            ],
        ),
        migrations.CreateModel(
            name='StudyWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ManyToManyField(to='mbou.StudyDay')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mbou.Form')),
            ],
        ),
    ]
