# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0004_remove_studyday_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('designator', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='studyweek',
            name='days',
        ),
        migrations.RemoveField(
            model_name='studyweek',
            name='form',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='StudyDay',
        ),
        migrations.DeleteModel(
            name='StudyWeek',
        ),
    ]
