# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0008_auto_20170816_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title_id',
            field=models.TextField(default=''),
        ),
    ]
