# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0009_document_title_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(choices=[('GR', 'success'), ('DB', 'primary'), ('B', 'default'), ('RE', 'danger'), ('BL', 'info')], default='default', max_length=2)),
            ],
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='document',
            name='categories',
            field=models.ManyToManyField(to='mbou.DocumentCategory'),
        ),
    ]
