# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0010_auto_20170816_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcategory',
            name='name_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
