# Generated by Django 2.0.6 on 2018-06-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0011_documentcategory_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sform',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='StudyForm',
        ),
    ]
