# Generated by Django 2.0.6 on 2018-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0013_auto_20180704_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='full_name',
            field=models.TextField(default=''),
        ),
    ]
