# Generated by Django 2.0.6 on 2018-07-09 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0014_staffmember_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.TextField(default='', max_length=60)),
                ('title_id', models.TextField(default='', max_length=70, primary_key=True, serialize=False)),
                ('description', models.TextField(default='', max_length=360)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photos_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-pub_date', '-views_count'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(default='', max_length=60)),
                ('description', models.TextField(default='', max_length=360)),
                ('photo', models.ImageField(upload_to='photos')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('album', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='mbou.Album')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-pub_date', '-views_count']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date', '-views_count']},
        ),
        migrations.AddField(
            model_name='document',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
