# Generated by Django 2.0.6 on 2018-07-12 23:04

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('mbou', '0015_auto_20180709_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
