# Generated by Django 2.0.6 on 2019-02-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0017_remove_album_photos_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='doc_url',
            field=models.TextField(default=''),
        ),
    ]
