# Generated by Django 2.0.6 on 2020-01-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0019_news_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.FileField(blank=True, default=None, upload_to='pics'),
        ),
    ]
