# Generated by Django 2.0.6 on 2020-01-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0020_auto_20200127_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pics'),
        ),
    ]
