# Generated by Django 2.0.6 on 2020-01-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0021_auto_20200127_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.FileField(blank=True, default=None, upload_to='pics'),
        ),
    ]
