# Generated by Django 2.0.6 on 2021-05-20 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mbou', '0022_auto_20200127_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('doc', models.FileField(upload_to='food')),
                ('is_minor', models.CharField(max_length=2)),
                ('title_id', models.CharField(max_length=15)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('views_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
